#REQUIRED

DB_USER = '<YOUR_DB_USER>'
DB_HOST = '<YOUR_DB_HOST>'
DB_PORT = '<YOUR_DB_PORT>'
DB_NAME = '<YOUR_DB_NAME>'
DB_PASSWORD = '<YOUR_DB_PASSWORD>'
DB_TIMEOUT = 20 # YOUR_DB_TIMEOUT
GCM_KEY = '<YOUR_GCM_KEY>'

# OPTIONAL
SAMSUNG_LICENSE = '<YOUR_SAMSUNG_KEY>'

