#This file just helps in making sure that we are not using any hardcoded string anywhere.
class Constants:

    USER_TABLE= 'users'
    USER_TABLE_ID= 'id'
    USER_TABLE_EMAIL= 'email'
    USER_TABLE_NAME = 'name'
    USER_TABLE_TEAM = 'team_id'
    USER_TABLE_ROLE = 'role_id'
    USER_TABLE_POLICY = 'policy_id'
    USER_TABLE_COMPANY = 'company_id'
    USER_TABLE_DELETED = 'deleted'
    USER_TABLE_CREATED_ON = 'created_on'
    USER_TABLE_MODIFIED_ON = 'modified_on'

    TEAM_TABLE = 'teams'
    TEAM_TABLE_ID = 'id'
    TEAM_TABLE_NAME = 'name'
    TEAM_TABLE_COMPANY = 'company_id'
    TEAM_TABLE_CREATED_ON = 'created_on'
    TEAM_TABLE_POLICY = 'policy_id'
    TEAM_TABLE_LAST_MODIFIED = 'modified_on'
    TEAM_TABLE_DELETED = 'deleted'

    DEVICE_TABLE = 'devices' #140283
    DEVICE_TABLE_ID = 'id'
    DEVICE_TABLE_USER = 'user_id'
    DEVICE_TABLE_NAME = 'name' # For future...
    DEVICE_TABLE_UDID = 'udid'  #May contain UDID or IMEI depending on the OS.
    DEVICE_TABLE_OS = 'os'
    DEVICE_TABLE_DELETED = 'deleted'
    DEVICE_TABLE_OS_VERSION = 'os_version'
    DEVICE_TABLE_CREATED_ON = 'created_on'
    DEVICE_TABLE_MODIFIED_ON = 'modified_on'

    VIOLATION_TABLE = 'violations'
    VIOLATION_TABLE_ID = 'id'
    VIOLATION_TABLE_DEVICE = 'device_id'
    VIOLATION_TABLE_TIMESTAMP = 'timestamp'
    VIOLATION_TABLE_DELETED = 'deleted'

    ENROLLMENT_TABLE = 'enrollments'
    ENROLLMENT_TABLE_ID = 'id'
    ENROLLMENT_TABLE_USER = 'user_id'
    ENROLLMENT_TABLE_DEVICE = 'device_id'
    ENROLLMENT_TABLE_PASSWORD = 'password'
    ENROLLMENT_TABLE_ENROLLED_ON = 'enrolled_on'
    ENROLLMENT_TABLE_SENT_ON = 'sent_on'
    ENROLLMENT_TABLE_IS_ENROLLED = 'is_enrolled'

    POLICY_TABLE = 'policies'
    POLICY_TABLE_ID = 'id'
    POLICY_TABLE_NEW_ATTRIBUTES = 'new_attributes'
    POLICY_TABLE_OLD_ATTRIBUTES = 'old_attributes'
    POLICY_TABLE_CREATED_ON = 'created_on'
    POLICY_TABLE_MODIFIED_ON = 'modified_on'
    POLICY_TABLE_DELETED = 'deleted'

    ROLE_TABLE = 'roles'
    ROLE_TABLE_ID = 'id'
    ROLE_TABLE_NAME = 'name'
    ROLE_TABLE_POLICY = 'policy_id'
    ROLE_TABLE_CREATED_ON = 'created_on'
    ROLE_TABLE_LAST_MODIFIED = 'modified_on'
    ROLE_TABLE_COMPANY = 'company_id'
    ROLE_TABLE_DELETED = 'deleted'

    COMPANY_TABLE = 'companies'
    COMPANY_TABLE_ID = 'id'
    COMPANY_TABLE_NAME = 'name'
    COMPANY_TABLE_POLICY = 'policy_id'
    COMPANY_TABLE_CREATED_ON = 'created_on'
    COMPANY_TABLE_MODIFIED_ON = 'modified_on'
    COMPANY_TABLE_DELETED = 'deleted'


    LOGIN_TABLE = 'admin_profile'
    LOGIN_TABLE_ID = 'id'
    LOGIN_TABLE_NAME = 'name'
    LOGIN_TABLE_EMAIL = 'email'
    LOGIN_TABLE_USERNAME = 'email'
    # LOGIN_TABLE_PASSWORD = 'password'
    LOGIN_TABLE_COMPANY = 'company_id'
    LOGIN_TABLE_PASSWORD = 'login_id'
    LOGIN_TABLE_CREATED_ON = 'created_on'
    LOGIN_TABLE_MODIFIED_ON = 'modified_on'
    LOGIN_TABLE_DELETED = 'deleted'

    SESSION_TABLE = 'sessions'
    SESSION_TABLE_ID = 'id'
    SESSION_TABLE_USER = 'user_id'
    SESSION_TABLE_CREATED_ON = 'created_on'
    SESSION_TABLE_DESTROYED_ON = 'destroyed_on'
    SESSION_TABLE_IP = 'ip'
    SESSION_TABLE_INVALID = 'invalid'
    SESSION_TABLE_USER_AGENT= 'user_agent'

    LOGS_TABLE = 'logs'
    LOGS_TABLE_ID = 'id'
    LOGS_TABLE_COMPONENT_TYPE = 'component_type'
    LOGS_TABLE_COMPONENT_TYPE_USER = 'user'
    LOGS_TABLE_COMPONENT_TYPE_ROLE = 'role'
    LOGS_TABLE_COMPONENT_TYPE_TEAM = 'team'
    LOGS_TABLE_COMPONENT_TYPE_DEVICE = 'device'
    LOGS_TABLE_COMPONENT_TYPE_POLICY = 'policy'
    LOGS_TABLE_COMPONENT_TYPE_ENROLLMENT = 'enrollment'
    LOGS_TABLE_COMPONENT_ID = 'component_id'
    LOGS_TABLE_LEVEL = 'level'
    LOGS_TABLE_TAG = 'tag'
    LOGS_TABLE_MESSAGE = 'message'
    LOGS_TABLE_RAW = 'raw'
    LOGS_TABLE_COMPANY = 'company_id'
    LOGS_TABLE_TIMESTAMP = 'timestamp'

    #Device details table. Add single table
    DEVICE_DETAILS_TABLE = 'device_details'
    DEVICE_DETAILS_TABLE_ID = 'id'
    DEVICE_DETAILS_TABLE_DEVICE = 'device_id'
    DEVICE_DETAILS_TABLE_PUSH_MAGIC = 'push_magic'
    DEVICE_DETAILS_TABLE_DEVICE_TOKEN = 'token'
    DEVICE_DETAILS_TABLE_UNLOCK_TOKEN = 'unlock_token'
    DEVICE_DETAILS_TABLE_GCM_REG_NO = 'gcm'
    DEVICE_DETAILS_TABLE_MESSAGE_TOKEN = 'message_token'
    DEVICE_DETAILS_TABLE_EXTRAS = 'extras'


    COMMAND_TABLE = 'ios_commands'
    COMMAND_TABLE_ID = 'id'
    COMMAND_TABLE_COMMAND_UUID = 'command_uuid' #*
    COMMAND_TABLE_DEVICE = 'device_id'
    COMMAND_TABLE_EXECUTED = 'executed' # get_not_executed(udid)
    COMMAND_TABLE_ACTION = 'action'
    COMMAND_TABLE_RESULT = 'result' #update_result(uuid,udid,res)
    COMMAND_TABLE_ATTRIBUTE = 'attribute'
    COMMAND_TABLE_SENT_ON = 'sent_on'
    COMMAND_TABLE_EXECUTED_ON = 'executed_on'


    SAMSUNG_COMMANDS_TABLE = 'samsung_commands'
    SAMSUNG_COMMANDS_TABLE_ID = 'id'
    SAMSUNG_COMMANDS_TABLE_UUID = 'command_uuid'
    SAMSUNG_COMMANDS_TABLE_DEVICE = 'device_id'
    SAMSUNG_COMMANDS_TABLE_EXECUTED = 'executed'
    SAMSUNG_COMMANDS_TABLE_ACTION = 'action'
    SAMSUNG_COMMANDS_TABLE_ACTION_SETUP = 'setup'
    SAMSUNG_COMMANDS_TABLE_RESULT = 'result'
    SAMSUNG_COMMANDS_TABLE_ATTRIBUTE = 'attribute'
    SAMSUNG_COMMANDS_TABLE_TIMESTAMP = 'timestamp'
